### ISSUE TITLE
Upload ggalign to conda

### ISSUE THREAD

**Issue by carcarre11** [Yunuuuu/ggalign#16]
First of all, thank you for developing this package. It's great and very useful! As a suggestion, it would be great to upload the package to Conda to make it easier to integrate into an environment-based workflow.

Thank you!

**Comment by Yunuuuu** [comment]
Thank you for your kind words and valuable suggestion! I appreciate your feedback and will take a look on how to add an R package to the Conda channel.

Thanks again!

**Comment by Yunuuuu** [comment]
I noticed that `r-ggalign` has been successfully deposited on the Conda-Forge channel. You can find it at this link: https://anaconda.org/conda-forge/r-ggalign.
