### ISSUE TITLE
Complex Examples Code

### ISSUE THREAD

**Issue by Sayyam-Shah** [Yunuuuu/ggalign#19]
Hi!

Thank you so much for this amazing package!! Would you be able to share the code for the complex examples shown in the readme? I would love to use it as an example to create my own figures with ggalign.

Thank you!

**Comment by Yunuuuu** [comment]
Thank you for your kind words about the package! I’m glad you find it useful. You can check out the complex examples at this link: [More Examples](https://yunuuuu.github.io/ggalign/articles/more-examples.html). If you’re using the development version, here’s the link for that: [Development Version Examples](https://yunuuuu.github.io/ggalign/dev/articles/more-examples.html). I hope this helps you create your own figures with ggalign!

**Comment by Yunuuuu** [comment]
For now, I'll close this issue as it has been completed. If you have any questions related to the code, feel free to open another issue.

**Comment by EvoLandEco** [comment]
The link is no longer valid, could you please share again the examples shown in README? Some of them are rather hard to reproduce.

Thank you in advance!

**Comment by EvoLandEco** [comment]
Found the source code at another repo at https://github.com/Yunuuuu/ggalign-research/blob/main/Figure%203.qmd

In case useful to anyone
