### ISSUE TITLE
maftools CNV object support

### ISSUE THREAD

**Issue by Yunuuuu** [Yunuuuu/ggalign#24]

**Comment by wangzunq** [comment]
What I understand is maftools have this to be integrated with variant oncoplot OR standalone oncoplot. Not sure it can be extracted from MAF obj to be used with ggalign to plot yet. If future development highly consider this feature, that would be great.

**Comment by Yunuuuu** [comment]
should fix by ff22653b259eafdbeac243a46f0de63d7a97998d

The vignette has also been updated.

**Comment by Yunuuuu** [comment]
If you found issues, fill free to open a new issue. Now I'll close this since completed
